{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e2641235-2bcd-4fef-9344-d1b65d46460d",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0a4e3aeb-f99c-47ff-b1f9-ad2fd4bbc614",
   "metadata": {},
   "source": [
    "We use the Exception class as a base class while creating a custom exception because it provides a standardized way of defining and handling exceptions in Python.\n",
    "\n",
    "The Exception class is the base class for all exceptions in Python and provides a set of methods that are useful for exception handling. By inheriting from the Exception class, we can define our own exception classes that inherit all the features and functionality of the base class, such as the ability to add custom error messages and to handle exceptions in a standardized way.\n",
    "\n",
    "When we create a custom exception, we usually want to add some custom functionality to the exception class, such as custom error messages or additional attributes. By inheriting from the Exception class, we can add these custom features to our exception class while still maintaining the standard behavior of an exception in Python.\n",
    "\n",
    "In summary, using the Exception class as the base class for a custom exception allows us to create exceptions that are consistent with the Python language and provides a standard way of handling exceptions in our code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49b7caa6-19cb-4a46-931c-aabc85992264",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "83ab1fb8-38d9-4001-a17d-adf63f0e0dbe",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1e46ecd6-ae10-4307-a443-a0805f965f8a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "  Exception\n",
      "    TypeError\n",
      "      FloatOperation\n",
      "      MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "      ModuleNotFoundError\n",
      "      ZipImportError\n",
      "    OSError\n",
      "      ConnectionError\n",
      "        BrokenPipeError\n",
      "        ConnectionAbortedError\n",
      "        ConnectionRefusedError\n",
      "        ConnectionResetError\n",
      "          RemoteDisconnected\n",
      "      BlockingIOError\n",
      "      ChildProcessError\n",
      "      FileExistsError\n",
      "      FileNotFoundError\n",
      "      IsADirectoryError\n",
      "      NotADirectoryError\n",
      "      InterruptedError\n",
      "        InterruptedSystemCall\n",
      "      PermissionError\n",
      "      ProcessLookupError\n",
      "      TimeoutError\n",
      "      UnsupportedOperation\n",
      "      itimer_error\n",
      "      herror\n",
      "      gaierror\n",
      "      SSLError\n",
      "        SSLCertVerificationError\n",
      "        SSLZeroReturnError\n",
      "        SSLWantWriteError\n",
      "        SSLWantReadError\n",
      "        SSLSyscallError\n",
      "        SSLEOFError\n",
      "      Error\n",
      "        SameFileError\n",
      "      SpecialFileError\n",
      "      ExecError\n",
      "      ReadError\n",
      "      URLError\n",
      "        HTTPError\n",
      "        ContentTooShortError\n",
      "      BadGzipFile\n",
      "    EOFError\n",
      "      IncompleteReadError\n",
      "    RuntimeError\n",
      "      RecursionError\n",
      "      NotImplementedError\n",
      "        ZMQVersionError\n",
      "        StdinNotImplementedError\n",
      "      _DeadlockError\n",
      "      BrokenBarrierError\n",
      "      BrokenExecutor\n",
      "        BrokenThreadPool\n",
      "      SendfileNotAvailableError\n",
      "      ExtractionError\n",
      "      VariableError\n",
      "    NameError\n",
      "      UnboundLocalError\n",
      "    AttributeError\n",
      "      FrozenInstanceError\n",
      "    SyntaxError\n",
      "      IndentationError\n",
      "        TabError\n",
      "    LookupError\n",
      "      IndexError\n",
      "      KeyError\n",
      "        NoSuchKernel\n",
      "        UnknownBackend\n",
      "      CodecRegistryError\n",
      "    ValueError\n",
      "      UnicodeError\n",
      "        UnicodeEncodeError\n",
      "        UnicodeDecodeError\n",
      "        UnicodeTranslateError\n",
      "      UnsupportedOperation\n",
      "      JSONDecodeError\n",
      "      SSLCertVerificationError\n",
      "      Error\n",
      "      UnsupportedDigestmodError\n",
      "      IllegalMonthError\n",
      "      IllegalWeekdayError\n",
      "      ParserError\n",
      "      ClassNotFound\n",
      "      ClipboardEmpty\n",
      "      MessageDefect\n",
      "        NoBoundaryInMultipartDefect\n",
      "        StartBoundaryNotFoundDefect\n",
      "        CloseBoundaryNotFoundDefect\n",
      "        FirstHeaderLineIsContinuationDefect\n",
      "        MisplacedEnvelopeHeaderDefect\n",
      "        MissingHeaderBodySeparatorDefect\n",
      "        MultipartInvariantViolationDefect\n",
      "        InvalidMultipartContentTransferEncodingDefect\n",
      "        UndecodableBytesDefect\n",
      "        InvalidBase64PaddingDefect\n",
      "        InvalidBase64CharactersDefect\n",
      "        InvalidBase64LengthDefect\n",
      "        HeaderDefect\n",
      "          InvalidHeaderDefect\n",
      "          HeaderMissingRequiredValue\n",
      "          NonPrintableDefect\n",
      "          ObsoleteHeaderDefect\n",
      "          NonASCIILocalPartDefect\n",
      "          InvalidDateDefect\n",
      "      MacroToEdit\n",
      "      InvalidFileException\n",
      "      UnequalIterablesError\n",
      "      InvalidVersion\n",
      "      _InvalidELFFileHeader\n",
      "      InvalidWheelFilename\n",
      "      InvalidSdistFilename\n",
      "      InvalidSpecifier\n",
      "      InvalidMarker\n",
      "      UndefinedComparison\n",
      "      UndefinedEnvironmentName\n",
      "      InvalidRequirement\n",
      "        RequirementParseError\n",
      "      InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "      FloatingPointError\n",
      "      OverflowError\n",
      "      ZeroDivisionError\n",
      "        DivisionByZero\n",
      "        DivisionUndefined\n",
      "      DecimalException\n",
      "        Clamped\n",
      "        Rounded\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Inexact\n",
      "          Underflow\n",
      "          Overflow\n",
      "        Subnormal\n",
      "          Underflow\n",
      "        DivisionByZero\n",
      "        FloatOperation\n",
      "        InvalidOperation\n",
      "          ConversionSyntax\n",
      "          DivisionImpossible\n",
      "          DivisionUndefined\n",
      "          InvalidContext\n",
      "    SystemError\n",
      "      CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "      UserWarning\n",
      "        GetPassWarning\n",
      "        FormatterWarning\n",
      "      EncodingWarning\n",
      "      DeprecationWarning\n",
      "        ProvisionalWarning\n",
      "      PendingDeprecationWarning\n",
      "      SyntaxWarning\n",
      "      RuntimeWarning\n",
      "        ProactorSelectorThreadWarning\n",
      "        UnknownTimezoneWarning\n",
      "        PEP440Warning\n",
      "      FutureWarning\n",
      "        ProvisionalCompleterWarning\n",
      "      ImportWarning\n",
      "      UnicodeWarning\n",
      "      BytesWarning\n",
      "      ResourceWarning\n",
      "      DeprecatedTzFormatWarning\n",
      "      PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "      CalledProcessError\n",
      "      TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "      CancelledError\n",
      "      TimeoutError\n",
      "      InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "      ZMQError\n",
      "        ContextTerminated\n",
      "        Again\n",
      "        InterruptedSystemCall\n",
      "      ZMQBindError\n",
      "      NotDone\n",
      "    PickleError\n",
      "      PicklingError\n",
      "      UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "      ConfigLoaderError\n",
      "        ArgumentError\n",
      "      ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "      MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "      NoSectionError\n",
      "      DuplicateSectionError\n",
      "      DuplicateOptionError\n",
      "      NoOptionError\n",
      "      InterpolationError\n",
      "        InterpolationMissingOptionError\n",
      "        InterpolationSyntaxError\n",
      "        InterpolationDepthError\n",
      "      ParsingError\n",
      "        MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "      EOF\n",
      "      TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "      TryNext\n",
      "      UsageError\n",
      "      StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "      InvalidAliasError\n",
      "    Error\n",
      "      InterfaceError\n",
      "      DatabaseError\n",
      "        InternalError\n",
      "        OperationalError\n",
      "        ProgrammingError\n",
      "        IntegrityError\n",
      "        DataError\n",
      "        NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "      IndexSizeErr\n",
      "      DomstringSizeErr\n",
      "      HierarchyRequestErr\n",
      "      WrongDocumentErr\n",
      "      InvalidCharacterErr\n",
      "      NoDataAllowedErr\n",
      "      NoModificationAllowedErr\n",
      "      NotFoundErr\n",
      "      NotSupportedErr\n",
      "      InuseAttributeErr\n",
      "      InvalidStateErr\n",
      "      SyntaxErr\n",
      "      InvalidModificationErr\n",
      "      NamespaceErr\n",
      "      InvalidAccessErr\n",
      "      ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "      InternalError\n",
      "      WrongVersion\n",
      "      RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "      MessageParseError\n",
      "        HeaderParseError\n",
      "        BoundaryError\n",
      "      MultipartConversionError\n",
      "      CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "      NotConnected\n",
      "      InvalidURL\n",
      "      UnknownProtocol\n",
      "      UnknownTransferEncoding\n",
      "      UnimplementedFileMode\n",
      "      IncompleteRead\n",
      "      ImproperConnectionState\n",
      "        CannotSendRequest\n",
      "        CannotSendHeader\n",
      "        ResponseNotReady\n",
      "      BadStatusLine\n",
      "        RemoteDisconnected\n",
      "      LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "      NoSuchProcess\n",
      "        ZombieProcess\n",
      "      AccessDenied\n",
      "      TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "      ProtocolError\n",
      "      ResponseError\n",
      "      Fault\n",
      "    ParseBaseException\n",
      "      ParseException\n",
      "      ParseFatalException\n",
      "        ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "      VersionConflict\n",
      "        ContextualVersionConflict\n",
      "      DistributionNotFound\n",
      "      UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "  GeneratorExit\n",
      "  SystemExit\n",
      "  KeyboardInterrupt\n",
      "  CancelledError\n",
      "  AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exc_type=BaseException, prefix=''):\n",
    "    print(prefix + str(exc_type.__name__))\n",
    "    for sub_exc_type in exc_type.__subclasses__():\n",
    "        print_exception_hierarchy(sub_exc_type, prefix + '  ')\n",
    "\n",
    "print_exception_hierarchy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63fc06a9-4e40-4703-a5f7-883c4df03a53",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "8707cc8e-1ea3-4b7f-a3df-86bf6be838a4",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1b333889-f3c3-4d78-87c0-97454bda9b80",
   "metadata": {},
   "source": [
    "The ArithmeticError class is a built-in exception class in Python that represents errors that occur during arithmetic operations. This class serves as the base class for other arithmetic-related exceptions.\n",
    "\n",
    "Some of the errors defined in the ArithmeticError class include:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6ea197ee-2b72-471d-90fd-55dc888a14d3",
   "metadata": {},
   "source": [
    " 1. ZeroDivisionError - This error occurs when a number is divided by zero. For example, dividing 5 by 0 will raise a ZeroDivisionError:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fee6ea46-0d77-470d-aa0a-45a2a6165c33",
   "metadata": {},
   "source": [
    ">>> 5 / 0\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ZeroDivisionError: division by zero"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0be272eb-b9d6-4e6d-aeeb-0ed2cd58acbc",
   "metadata": {},
   "source": [
    " 2. OverflowError - This error occurs when the result of an arithmetic operation is too large to be represented by the available memory or datatype. For example, adding two very large numbers may result in an OverflowError:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db9e1bf2-109c-4ecb-ac42-829791c5acf7",
   "metadata": {},
   "outputs": [],
   "source": [
    ">>> import sys\n",
    ">>> sys.maxsize + 1\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "OverflowError: Python int too large to convert to C long\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b1499737-faee-464b-9543-11ce51bbdf5a",
   "metadata": {},
   "source": [
    " 3. FloatingPointError - This error occurs when an error arises during a floating-point calculation. For example, taking the square root of a negative number will result in a FloatingPointError:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f26c674b-98cd-436c-8741-982d8a542fc2",
   "metadata": {},
   "outputs": [],
   "source": [
    ">>> import math\n",
    ">>> math.sqrt(-1)\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "ValueError: math domain error\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "67fa29aa-85ed-4daa-838a-7b11e01c4f4d",
   "metadata": {},
   "source": [
    "Note that while FloatingPointError is not a direct subclass of ArithmeticError, it is related to arithmetic operations and can be raised during such operations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3da0e231-6bf4-4d57-a817-8c927d1bc2ce",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "4d0e6a0c-7741-4181-b385-9e92a789ff07",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fb04cefb-d4b1-48e3-8e5b-96672b039650",
   "metadata": {},
   "source": [
    "LookupError is a base class for errors that occur when trying to access a sequence or mapping using a key or index that does not exist. It is a subclass of the Exception class in Python.\n",
    "\n",
    "The main purpose of using the LookupError class is to catch errors that occur when trying to access a sequence or mapping using an invalid key or index. By using this class, we can handle such errors more easily and provide appropriate error messages to the user.\n",
    "\n",
    "Two common subclasses of LookupError are KeyError and IndexError.\n",
    "\n",
    "KeyError is raised when trying to access a dictionary key that does not exist. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a051a827-1597-40b3-ba2d-234c658bd69e",
   "metadata": {},
   "outputs": [],
   "source": [
    ">>> my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    ">>> my_dict['d']\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "KeyError: 'd'\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0be9f672-016f-458c-9bd3-bebcdb95918f",
   "metadata": {},
   "source": [
    "In this example, my_dict['d'] raises a KeyError because the key 'd' does not exist in the dictionary.\n",
    "\n",
    "IndexError is raised when trying to access a sequence using an index that is out of range. For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "448ab88e-9eb9-4f31-a4bf-24c95e91f133",
   "metadata": {},
   "outputs": [],
   "source": [
    ">>> my_list = [1, 2, 3]\n",
    ">>> my_list[3]\n",
    "Traceback (most recent call last):\n",
    "  File \"<stdin>\", line 1, in <module>\n",
    "IndexError: list index out of range"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "20931818-32bb-4300-b711-a511152f0463",
   "metadata": {},
   "source": [
    "In this example, my_list[3] raises an IndexError because the index 3 is out of range for the list, which only has three elements.\n",
    "\n",
    "In summary, the LookupError class is used to handle errors that occur when trying to access a sequence or mapping using an invalid key or index, and KeyError and IndexError are specific subclasses of LookupError that are raised in different situations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fec709d4-4d05-43c6-9048-764736342813",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "723aa3a6-5fa8-472b-8cb7-ee6bd27b23bf",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2568103b-11d4-4d52-8ff2-0c96f9662530",
   "metadata": {},
   "source": [
    "In Python, ImportError and ModuleNotFoundError are both errors that occur when a module or package cannot be imported or found. However, they have slightly different meanings.\n",
    "\n",
    "ImportError is a general error that occurs when there is a problem importing a module or package. This error can occur for various reasons, such as when the module or package is not installed or when the module is not in the Python search path. It can also occur when there is an error in the module's code or when the module depends on another module that cannot be imported.\n",
    "\n",
    "ModuleNotFoundError is a more specific error that occurs when Python cannot find a module or package with the specified name. This error was introduced in Python 3.6 and is raised when the specified module cannot be found in the usual places where Python searches for modules. This error is raised when the module is not installed or is not in the Python search path."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f39836a-20bc-41f5-8867-161955ff8f18",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "dfc54bba-7c44-4a20-b51f-ed634771045a",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "11827866-40be-4cf7-a830-119f82f3df8d",
   "metadata": {},
   "source": [
    "   1. use always specific exception\n",
    "   2. print always a proper message\n",
    "   3. always try to log your error\n",
    "   4. always avoid to write a multiple exception \n",
    "   5. document all the error\n",
    "   6. cleanup all the resources \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f581dfd-f090-45fb-900d-8394c82876c5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
